In [1]:
import pandas as pd

In [2]:
train_data_file_name = "train_data.csv"
test_data_file_name = "test_data.csv"

In [3]:
# read data
print("Reading files ...")
try:
    print(train_data_file_name + " ... ", end = "")
    train = pd.read_csv(train_data_file_name)
    print("finished (1/2)")
    print(test_data_file_name + " ... ", end = "")
    test = pd.read_csv(test_data_file_name)
    print("finished (2/2)")
    print("File loading completed!")
except FileNotFoundError as fnf_error:
    print(fnf_error)

Reading files ...
train_data.csv ... finished (1/2)
test_data.csv ... finished (2/2)
File loading completed!

In [4]:
print(train.shape)
print(test.shape)

(15220, 214)
(10106, 214)

In [5]:
train

,user_id,event_id,interested,un_interested,invited,friend_yes,friend_maybe,friend_invited,friend_no,same_gender_yes,...,interest_c_190,interest_c_191,interest_c_192,interest_c_193,interest_c_194,interest_c_195,interest_c_196,interest_c_197,interest_c_198,interest_c_199
0,3044012,1918771225,0,0,0,0,0,3,3,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,3044012,1502284248,0,0,0,0,0,1,0,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,3044012,2529072432,1,0,0,0,0,2,0,0.833333,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,3044012,3072478280,0,0,0,1,0,0,0,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,3044012,1390707377,0,0,0,0,0,2,0,0.333333,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15215,4293103086,2750873665,0,0,0,0,1,0,0,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
15216,4293103086,4084655790,0,0,0,1,0,1,0,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
15217,4293103086,598708806,0,0,0,1,1,3,1,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
15218,4293103086,604179853,0,0,0,0,1,0,1,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
15219,4293103086,2351245308,1,0,0,0,0,1,0,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [6]:
test

,user_id,event_id,interested,un_interested,invited,friend_yes,friend_maybe,friend_invited,friend_no,same_gender_yes,...,interest_c_190,interest_c_191,interest_c_192,interest_c_193,interest_c_194,interest_c_195,interest_c_196,interest_c_197,interest_c_198,interest_c_199
0,1776192,2877501688,-1,-1,0,1,0,1,0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,1776192,3025444328,-1,-1,0,1,0,11,2,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,1776192,4078218285,-1,-1,0,0,0,7,0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,1776192,1024025121,-1,-1,0,0,0,3,0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,1776192,2972428928,-1,-1,0,0,0,3,0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10101,4289724715,2652356640,-1,-1,0,0,0,0,0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
10102,4289724715,3128167927,-1,-1,0,0,0,0,0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
10103,4289724715,645947926,-1,-1,0,0,0,0,0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
10104,4289724715,3547653054,-1,-1,0,0,0,0,0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
10105,4289724715,2769292935,-1,-1,0,0,0,0,0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [7]:
import random
import torch
import torch.nn as nn
import torch.optim as optim
import torchvision
import numpy as np
import d2l
from torchvision import datasets, transforms
import matplotlib.pyplot as plt
from IPython import display
import utils

In [8]:
train_total_size = 15220
training_size = 14000
validate_size = train_total_size - training_size
testing_size = 10106

training_data = torch.FloatTensor(train.iloc[: training_size, 4 :].values)
validate_data = torch.FloatTensor(train.iloc[training_size :, 4 :].values)
testing_data = torch.FloatTensor(test.iloc[:, 4 :].values)
training_label = torch.FloatTensor(train.iloc[: training_size, [2, 3]].values)
validate_label = torch.FloatTensor(train.iloc[training_size :, [2, 3]].values)
print("training_data size:", list(training_data.shape))
print("validate_data size:", list(validate_data.shape))
print("testing_data size:", list(testing_data.shape))
print("training_label size:", list(training_label.shape))
print("validate_label size:", list(validate_label.shape))

training_data size: [14000, 210]
validate_data size: [1220, 210]
testing_data size: [10106, 210]
training_label size: [14000, 2]
validate_label size: [1220, 2]

In [9]:
input_size, hidden1_size, hidden2_size, output_size = 210, 514, 128, 2
batch_size = 14000

In [10]:
class myNet(nn.Module):
    
    def __init__(self, input_size, hidden1_size, hidden2_size, output_size):        
        super(myNet, self).__init__()
        self.fc1 = nn.Linear(input_size, hidden1_size)
        self.relu1 = nn.ReLU()
        self.fc2 = nn.Linear(hidden1_size, hidden2_size)
        self.relu2 = nn.ReLU()
        self.fc3 = nn.Linear(hidden2_size, output_size)
        
    def forward(self, x):
        out = self.fc1(x)
        out.float()
        out = self.relu1(out)
        out = self.fc2(out)
        out = self.relu2(out)
        out = self.fc3(out)
        return out

In [11]:
net = myNet(input_size, hidden1_size, hidden2_size, output_size)

In [12]:
print(net)

myNet(
  (fc1): Linear(in_features=210, out_features=514, bias=True)
  (relu1): ReLU()
  (fc2): Linear(in_features=514, out_features=128, bias=True)
  (relu2): ReLU()
  (fc3): Linear(in_features=128, out_features=2, bias=True)
)

In [13]:
optimizer = optim.Adam(net.parameters(), lr=0.002)
loss_funtion = nn.MSELoss()

In [14]:
def load_array(data_arrays, batch_size, is_train=True):
    features, labels = data_arrays
    num_examples = len(labels)
    indices = list(range(num_examples))
    random.shuffle(indices)
    array = []
    for i in range(0, num_examples, batch_size):
        batch_indices = torch.tensor(indices[i : min(i + batch_size, num_examples - 1)])
        minibatch_features = features.index_select(0, batch_indices)
        minibatch_labels = labels.index_select(0, batch_indices)
        array.append((minibatch_features, minibatch_labels))
    train_loader = iter(array)
    return train_loader

In [15]:
Epchs = 1001

for epoch in range(Epchs):
    data_iter = load_array((training_data, training_label), batch_size)
    for batch_X, batch_y in data_iter:
        net.zero_grad()
        output = net(batch_X)
        loss = loss_funtion(output, batch_y)
        loss.backward()
        optimizer.step()
    if epoch % 100 == 0:
        print("loss for epoch ",epoch, " is ", loss.data)

loss for epoch  0  is  tensor(1.3804)
loss for epoch  100  is  tensor(0.0892)
loss for epoch  200  is  tensor(0.0612)
loss for epoch  300  is  tensor(0.0512)
loss for epoch  400  is  tensor(0.0449)
loss for epoch  500  is  tensor(0.0415)
loss for epoch  600  is  tensor(0.0396)
loss for epoch  700  is  tensor(0.0364)
loss for epoch  800  is  tensor(0.0346)
loss for epoch  900  is  tensor(0.0334)
loss for epoch  1000  is  tensor(0.0370)

In [16]:
train_result = net(training_data)
print(train_result.shape)
print("loss for train_data is: ", loss_funtion(train_result, training_label).data)

torch.Size([14000, 2])
loss for train_data is:  tensor(0.0351)

In [17]:
result = net(validate_data)
print(result.shape)
print("loss for train_data is: ", loss_funtion(result, validate_label).data)

torch.Size([1220, 2])
loss for train_data is:  tensor(0.2135)

In [19]:
import numpy as np
from sklearn import metrics
y = np.array([1, 1, 2, 2])
pred = np.array([0.1, 0.4, 0.35, 0.8])
fpr, tpr, thresholds = metrics.roc_curve(y, pred, pos_label=2)
metrics.auc(fpr, tpr)

ModuleNotFoundError: No module named 'sklearn'